export const REQUEST_PHOTOS = 'REQUEST_PHOTOS'
export const RECEIVE_PHOTOS = 'RECEIVE_PHOTOS'
export const UPDATE_PHOTO_SEARCH_STRING = 'UPDATE_PHOTO_SEARCH_STRING'
export const SHOW_PHOTO = 'SHOW_PHOTO'
